In [31]:
text = ['This is a line',
       'This is another line',
       'Completely different line']

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
#help(CountVectorizer)

## text to bag of words

In [42]:
cv = CountVectorizer()

In [43]:
# cv = CountVectorizer(stop_words='english')

In [44]:
sparse_matrix = cv.fit_transform(text) # it will create bag of words (BOW) from text

In [45]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [46]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

## BOW to TFIDF

In [47]:
from sklearn.feature_extraction.text import TfidfTransformer

In [48]:
tf = TfidfTransformer()

In [51]:
results = tf.fit_transform(sparse_matrix) # BOW --> TFIDF

In [55]:
results.todense()

array([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
        0.61980538],
       [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
        0.4804584 ],
       [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
        0.        ]])

In [56]:
results.toarray()

array([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
        0.61980538],
       [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
        0.4804584 ],
       [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
        0.        ]])

## Directly from text to TFIDF

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [58]:
tfidf = TfidfVectorizer()

In [61]:
tf_result = tfidf.fit_transform(text)

In [62]:
tf_result.toarray()

array([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
        0.61980538],
       [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
        0.4804584 ],
       [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
        0.        ]])